default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: cosplay

development:
  <<: *default
  database: videoGrab_development

test:
  <<: *default
  database: videoGrab_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>